datadump.location:
  author: D:\Project Data\ol_dump_authors_2021-10-13.txt
  works: D:\Project Data\ol_dump_works_2021-10-13.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: qGpkIfwEzTTyAOdRHRxOQKiv
      password: AijtyNymlijzieLpm0H.YIp7ZYXd89terMvPLIhS5h-9j5T5EhioMZ8itX.7NvZ9gq5L3PTzCuHhopPzdYrB6MtAsFb7PCI_0eN8wX33+NzZw0NeFz8GiedEMQ6bTMk_
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip


astra.db:
  id: 0540ecf9-7a21-4969-8b01-ea3da0581446-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:qGpkIfwEzTTyAOdRHRxOQKiv:4d05cea5e22b763c889e1e8543712ca15256fb9cef6d0960d32110169030c69d








